name: Test
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn --immutable
            - name: Run tests
              run: yarn test
            - name: Build Plugin
              run: yarn build
            - uses: actions/upload-artifact@v3
              with:
                  name: plugin
                  path: |
                      dist/
                      manifest.json
